server:
  port: 8080
  wait-time-in-ms-when-sync-empty: 3000

spring:
  profiles:
    active: native
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cliente_DB
      auto-index-creation: true

application-version: 1.0
